apiVersion: v2
name: course-app
description: A Helm chart for course-app with Redis (Bitnami) dependency
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "~19.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

